// Code generated by re2c 3.0 on Sat Mar  2 13:35:56 2024, DO NOT EDIT.
//line "py.re":1
package golexers

import (
	"bytes"
    "fmt"
)

//line "py.re":17


func py_lex_str(in *Input) TokenType {
	for {
		in.token = in.cursor
    
//line "py.go":18
{
	var yych byte
yyFillLabel0:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy3
	case '\'':
		goto yy4
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy5
	case '\\':
		goto yy7
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel0
			}
			goto yy19
		}
		goto yy1
	}
yy1:
	in.cursor += 1
yy2:
//line "py.re":23
	{ return STRING }
//line "py.go":52
yy3:
	in.cursor += 1
//line "py.re":25
	{ if in.state == STATE_STRINGLITERAL { in.state = STATE_NORMAL }; return STRING }
//line "py.go":57
yy4:
	in.cursor += 1
//line "py.re":26
	{ if in.state == STATE_CHARLITERAL { in.state = STATE_NORMAL }; return STRING }
//line "py.go":62
yy5:
	in.cursor += 1
yyFillLabel1:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy5
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel1
			}
		}
		goto yy6
	}
yy6:
//line "py.re":27
	{ return STRINGWORD }
//line "py.go":87
yy7:
	in.cursor += 1
yyFillLabel2:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy8
	case '\'':
		goto yy9
	case '?':
		goto yy10
	case '\\':
		goto yy11
	case 'a':
		goto yy12
	case 'b':
		goto yy13
	case 'f':
		goto yy14
	case 'n':
		goto yy15
	case 'r':
		goto yy16
	case 't':
		goto yy17
	case 'v':
		goto yy18
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel2
			}
		}
		goto yy2
	}
yy8:
	in.cursor += 1
//line "py.re":37
	{ return STRING }
//line "py.go":127
yy9:
	in.cursor += 1
//line "py.re":36
	{ return STRING }
//line "py.go":132
yy10:
	in.cursor += 1
//line "py.re":38
	{ return STRING }
//line "py.go":137
yy11:
	in.cursor += 1
//line "py.re":35
	{ return STRING }
//line "py.go":142
yy12:
	in.cursor += 1
//line "py.re":28
	{ return STRING }
//line "py.go":147
yy13:
	in.cursor += 1
//line "py.re":29
	{ return STRING }
//line "py.go":152
yy14:
	in.cursor += 1
//line "py.re":30
	{ return STRING }
//line "py.go":157
yy15:
	in.cursor += 1
//line "py.re":31
	{ return STRING }
//line "py.go":162
yy16:
	in.cursor += 1
//line "py.re":32
	{ return STRING }
//line "py.go":167
yy17:
	in.cursor += 1
//line "py.re":33
	{ return STRING }
//line "py.go":172
yy18:
	in.cursor += 1
//line "py.re":34
	{ return STRING }
//line "py.go":177
yy19:
//line "py.re":24
	{ return -1 }
//line "py.go":181
}
//line "py.re":43

	}
}

func py_lex_long_str(in *Input, start bool) TokenType {
	for {
		if start {
			in.raw_str_delim = in.data[in.token + 2:in.cursor - 1]
			start = false
		}
		in.token = in.cursor
    
//line "py.go":196
{
	var yych byte
yyFillLabel3:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy23
	case '\n':
		goto yy25
	case '"':
		goto yy26
	case '\'':
		goto yy27
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy28
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel3
			}
			goto yy35
		}
		goto yy21
	}
yy21:
	in.cursor += 1
yy22:
//line "py.re":55
	{ return STRING }
//line "py.go":236
yy23:
	in.cursor += 1
yyFillLabel4:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy23
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel4
			}
		}
		goto yy24
	}
yy24:
//line "py.re":59
	{ continue }
//line "py.go":259
yy25:
	in.cursor += 1
//line "py.re":57
	{ in.line += 1; continue }
//line "py.go":264
yy26:
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel5:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy30
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel5
			}
		}
		goto yy22
	}
yy27:
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel6:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy32
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel6
			}
		}
		goto yy22
	}
yy28:
	in.cursor += 1
yyFillLabel7:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy28
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel7
			}
		}
		goto yy29
	}
yy29:
//line "py.re":64
	{ return STRINGWORD }
//line "py.go":321
yy30:
	in.cursor += 1
yyFillLabel8:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy33
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel8
			}
		}
		goto yy31
	}
yy31:
	in.cursor = in.marker
	goto yy22
yy32:
	in.cursor += 1
yyFillLabel9:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy34
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel9
			}
		}
		goto yy31
	}
yy33:
	in.cursor += 1
//line "py.re":61
	{ if bytes.Equal(in.raw_str_delim, in.data[in.token:in.cursor]) { in.state = STATE_NORMAL; in.raw_str_delim = nil }; return STRING }
//line "py.go":359
yy34:
	in.cursor += 1
//line "py.re":62
	{ if bytes.Equal(in.raw_str_delim, in.data[in.token:in.cursor]) { in.state = STATE_NORMAL; in.raw_str_delim = nil }; return STRING }
//line "py.go":364
yy35:
//line "py.re":56
	{ return -1 }
//line "py.go":368
}
//line "py.re":65

	}
}

func py_lex_eol_comment(in *Input) TokenType {
	for {
		in.token = in.cursor
    
//line "py.go":379
{
	var yych byte
	yyaccept := 0
yyFillLabel10:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		fallthrough
	case 0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t':
		fallthrough
	case '\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&','\'','(',')','*','+',',','-','.','/':
		fallthrough
	case ':',';','<','=','>','?','@':
		fallthrough
	case '[','\\',']','^':
		fallthrough
	case '`':
		fallthrough
	case '{','|','}','~',0x7F:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel10
			}
			goto yy57
		}
		goto yy37
	case '\n':
		goto yy39
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy40
	case 0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy44
	case 0xE0:
		goto yy45
	case 0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy46
	case 0xF0:
		goto yy47
	case 0xF1,0xF2,0xF3:
		goto yy48
	case 0xF4:
		goto yy49
	default:
		goto yy42
	}
yy37:
	yyaccept = 0
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel11:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		fallthrough
	case 0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,'\t':
		fallthrough
	case '\v','\f','\r',0x0E,0x0F,0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,' ','!','"','#','$','%','&','\'','(',')','*','+',',','-','.','/':
		fallthrough
	case ':',';','<','=','>','?','@':
		fallthrough
	case '[','\\',']','^':
		fallthrough
	case '`':
		fallthrough
	case '{','|','}','~',0x7F:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel11
			}
			goto yy38
		}
		goto yy37
	case 0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,0xCF,0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF:
		goto yy50
	case 0xE0:
		goto yy52
	case 0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,0xEF:
		goto yy53
	case 0xF0:
		goto yy54
	case 0xF1,0xF2,0xF3:
		goto yy55
	case 0xF4:
		goto yy56
	default:
		goto yy38
	}
yy38:
//line "py.re":77
	{ return COMMENT }
//line "py.go":476
yy39:
	in.cursor += 1
//line "py.re":74
	{ in.state = STATE_NORMAL; in.cursor -= 1; return END }
//line "py.go":481
yy40:
	in.cursor += 1
yyFillLabel12:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy40
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel12
			}
		}
		goto yy41
	}
yy41:
//line "py.re":76
	{ return COMMENTWORD }
//line "py.go":506
yy42:
	in.cursor += 1
yy43:
//line "py.re":73
	{ continue }
//line "py.go":512
yy44:
	in.cursor += 1
yyFillLabel13:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy37
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel13
			}
		}
		goto yy43
	}
yy45:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel14:
	yych = peek(in)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy50
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel14
			}
		}
		goto yy43
	}
yy46:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel15:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy50
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel15
			}
		}
		goto yy43
	}
yy47:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel16:
	yych = peek(in)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy53
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel16
			}
		}
		goto yy43
	}
yy48:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel17:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy53
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel17
			}
		}
		goto yy43
	}
yy49:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel18:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy53
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel18
			}
		}
		goto yy43
	}
yy50:
	in.cursor += 1
yyFillLabel19:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy37
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel19
			}
		}
		goto yy51
	}
yy51:
	in.cursor = in.marker
	if (yyaccept == 0) {
		goto yy38
	} else {
		goto yy43
	}
yy52:
	in.cursor += 1
yyFillLabel20:
	yych = peek(in)
	switch (yych) {
	case 0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy50
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel20
			}
		}
		goto yy51
	}
yy53:
	in.cursor += 1
yyFillLabel21:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy50
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel21
			}
		}
		goto yy51
	}
yy54:
	in.cursor += 1
yyFillLabel22:
	yych = peek(in)
	switch (yych) {
	case 0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy53
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel22
			}
		}
		goto yy51
	}
yy55:
	in.cursor += 1
yyFillLabel23:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F,0x90,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0x98,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F,0xA0,0xA1,0xA2,0xA3,0xA4,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0xAD,0xAE,0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF:
		goto yy53
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel23
			}
		}
		goto yy51
	}
yy56:
	in.cursor += 1
yyFillLabel24:
	yych = peek(in)
	switch (yych) {
	case 0x80,0x81,0x82,0x83,0x84,0x85,0x86,0x87,0x88,0x89,0x8A,0x8B,0x8C,0x8D,0x8E,0x8F:
		goto yy53
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel24
			}
		}
		goto yy51
	}
yy57:
//line "py.re":75
	{ return END }
//line "py.go":713
}
//line "py.re":78

	}
}

func py_lex(in *Input) TokenType {
	for {
		in.token = in.cursor
        //fmt.Printf("start at %d\n", in.token)
		if in.state == STATE_STRINGLITERAL || in.state == STATE_CHARLITERAL {
			t := py_lex_str(in)
			if t >= 0 {
				return t
			}
		} else if (in.state == STATE_LONGSTRINGLITERAL) {
			t := py_lex_long_str(in, false)
			if t >= 0 {
				return t
			}
		} else if (in.state == STATE_EOLCOMMENT) {
			t := py_lex_eol_comment(in)
			if t >= 0 {
				return t
			}
		}

	    was_bol := in.bol
		in.bol = false
    
//line "py.go":744
{
	var yych byte
	yyaccept := 0
yyFillLabel25:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy60
	case '\n':
		goto yy62
	case '!':
		goto yy63
	case '"':
		goto yy65
	case '#':
		goto yy67
	case '$':
		fallthrough
	case 'A','B','C','D','E':
		fallthrough
	case 'G','H','I','J','K','L','M':
		fallthrough
	case 'O','P','Q','R','S':
		fallthrough
	case 'U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'b':
		fallthrough
	case 'h':
		fallthrough
	case 'j','k':
		fallthrough
	case 'm':
		fallthrough
	case 'q':
		fallthrough
	case 's':
		fallthrough
	case 'u','v':
		fallthrough
	case 'x':
		fallthrough
	case 'z':
		goto yy68
	case '%':
		goto yy71
	case '&':
		goto yy72
	case '\'':
		goto yy74
	case '(':
		goto yy76
	case ')':
		goto yy77
	case '*':
		goto yy78
	case '+':
		goto yy79
	case ',':
		goto yy80
	case '-':
		goto yy81
	case '.':
		goto yy83
	case '/':
		goto yy84
	case '0':
		goto yy85
	case '1','2','3','4','5','6','7','8','9':
		goto yy87
	case ':':
		goto yy89
	case ';':
		goto yy91
	case '<':
		goto yy92
	case '=':
		goto yy94
	case '>':
		goto yy96
	case '?':
		goto yy98
	case '@':
		goto yy99
	case 'F':
		goto yy100
	case 'N':
		goto yy101
	case 'T':
		goto yy102
	case '[':
		goto yy103
	case '\\':
		goto yy104
	case ']':
		goto yy105
	case '^':
		goto yy106
	case 'a':
		goto yy107
	case 'c':
		goto yy108
	case 'd':
		goto yy109
	case 'e':
		goto yy110
	case 'f':
		goto yy111
	case 'g':
		goto yy112
	case 'i':
		goto yy113
	case 'l':
		goto yy114
	case 'n':
		goto yy115
	case 'o':
		goto yy116
	case 'p':
		goto yy117
	case 'r':
		goto yy118
	case 't':
		goto yy119
	case 'w':
		goto yy120
	case 'y':
		goto yy121
	case '{':
		goto yy122
	case '|':
		goto yy123
	case '}':
		goto yy125
	case '~':
		goto yy126
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel25
			}
			goto yy281
		}
		goto yy59
	}
yy59:
	in.cursor += 1
//line "py.re":112
	{ fmt.Printf("%s: %d: match %2x\n", in.filename, in.line, in.data[in.cursor-1]); continue }
//line "py.go":900
yy60:
	in.cursor += 1
yyFillLabel26:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy60
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel26
			}
		}
		goto yy61
	}
yy61:
//line "py.re":109
	{ in.bol = was_bol; continue }
//line "py.go":923
yy62:
	in.cursor += 1
//line "py.re":110
	{ in.bol = true; in.line += 1; continue }
//line "py.go":928
yy63:
	in.cursor += 1
yyFillLabel27:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy127
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel27
			}
		}
		goto yy64
	}
yy64:
//line "py.re":173
	{ return PUNCTUATION }
//line "py.go":947
yy65:
	yyaccept = 0
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel28:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy128
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel28
			}
		}
		goto yy66
	}
yy66:
//line "py.re":125
	{ in.state = STATE_STRINGLITERAL; return STRING }
//line "py.go":968
yy67:
	in.cursor += 1
//line "py.re":129
	{ in.state = STATE_EOLCOMMENT; return COMMENT }
//line "py.go":973
yy68:
	in.cursor += 1
yyFillLabel29:
	yych = peek(in)
yy69:
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel29
			}
		}
		goto yy70
	}
yy70:
//line "py.re":198
	{ return IDENTIFIER }
//line "py.go":1001
yy71:
	in.cursor += 1
//line "py.re":168
	{ return PUNCTUATION }
//line "py.go":1006
yy72:
	in.cursor += 1
yyFillLabel30:
	yych = peek(in)
	switch (yych) {
	case '&':
		goto yy130
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel30
			}
		}
		goto yy73
	}
yy73:
//line "py.re":169
	{ return PUNCTUATION }
//line "py.go":1025
yy74:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel31:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy131
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel31
			}
		}
		goto yy75
	}
yy75:
//line "py.re":126
	{ in.state = STATE_CHARLITERAL; return STRING }
//line "py.go":1046
yy76:
	in.cursor += 1
//line "py.re":179
	{ return PUNCTUATION }
//line "py.go":1051
yy77:
	in.cursor += 1
//line "py.re":180
	{ return PUNCTUATION }
//line "py.go":1056
yy78:
	in.cursor += 1
//line "py.re":167
	{ return PUNCTUATION }
//line "py.go":1061
yy79:
	in.cursor += 1
//line "py.re":164
	{ return PUNCTUATION }
//line "py.go":1066
yy80:
	in.cursor += 1
//line "py.re":178
	{ return PUNCTUATION }
//line "py.go":1071
yy81:
	in.cursor += 1
yyFillLabel32:
	yych = peek(in)
	switch (yych) {
	case '>':
		goto yy132
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel32
			}
		}
		goto yy82
	}
yy82:
//line "py.re":165
	{ return PUNCTUATION }
//line "py.go":1090
yy83:
	in.cursor += 1
//line "py.re":177
	{ return PUNCTUATION }
//line "py.go":1095
yy84:
	in.cursor += 1
//line "py.re":166
	{ return PUNCTUATION }
//line "py.go":1100
yy85:
	yyaccept = 2
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel33:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel33
			}
		}
		goto yy86
	case 'x':
		goto yy135
	default:
		goto yy134
	}
yy86:
//line "py.re":123
	{ return LITERAL }
//line "py.go":1123
yy87:
	in.cursor += 1
yyFillLabel34:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy87
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel34
			}
		}
		goto yy88
	}
yy88:
//line "py.re":121
	{ return LITERAL }
//line "py.go":1142
yy89:
	in.cursor += 1
yyFillLabel35:
	yych = peek(in)
	switch (yych) {
	case ':':
		goto yy136
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel35
			}
		}
		goto yy90
	}
yy90:
//line "py.re":194
	{ return PUNCTUATION }
//line "py.go":1161
yy91:
	in.cursor += 1
//line "py.re":176
	{ return PUNCTUATION }
//line "py.go":1166
yy92:
	in.cursor += 1
yyFillLabel36:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy137
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel36
			}
		}
		goto yy93
	}
yy93:
//line "py.re":188
	{ return PUNCTUATION }
//line "py.go":1185
yy94:
	in.cursor += 1
yyFillLabel37:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy138
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel37
			}
		}
		goto yy95
	}
yy95:
//line "py.re":185
	{ return PUNCTUATION }
//line "py.go":1204
yy96:
	in.cursor += 1
yyFillLabel38:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy139
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel38
			}
		}
		goto yy97
	}
yy97:
//line "py.re":189
	{ return PUNCTUATION }
//line "py.go":1223
yy98:
	in.cursor += 1
//line "py.re":193
	{ return PUNCTUATION }
//line "py.go":1228
yy99:
	in.cursor += 1
//line "py.re":115
	{ continue }
//line "py.go":1233
yy100:
	in.cursor += 1
yyFillLabel39:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel39
			}
		}
		goto yy70
	case 'a':
		goto yy140
	default:
		goto yy69
	}
yy101:
	in.cursor += 1
yyFillLabel40:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel40
			}
		}
		goto yy70
	case 'o':
		goto yy141
	default:
		goto yy69
	}
yy102:
	in.cursor += 1
yyFillLabel41:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel41
			}
		}
		goto yy70
	case 'r':
		goto yy142
	default:
		goto yy69
	}
yy103:
	in.cursor += 1
//line "py.re":183
	{ return PUNCTUATION }
//line "py.go":1289
yy104:
	in.cursor += 1
//line "py.re":108
	{ continue }
//line "py.go":1294
yy105:
	in.cursor += 1
//line "py.re":184
	{ return PUNCTUATION }
//line "py.go":1299
yy106:
	in.cursor += 1
//line "py.re":174
	{ return PUNCTUATION }
//line "py.go":1304
yy107:
	in.cursor += 1
yyFillLabel42:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel42
			}
		}
		goto yy70
	case 'n':
		goto yy143
	case 's':
		goto yy144
	default:
		goto yy69
	}
yy108:
	in.cursor += 1
yyFillLabel43:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel43
			}
		}
		goto yy70
	case 'l':
		goto yy146
	case 'o':
		goto yy147
	default:
		goto yy69
	}
yy109:
	in.cursor += 1
yyFillLabel44:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel44
			}
		}
		goto yy70
	case 'e':
		goto yy148
	default:
		goto yy69
	}
yy110:
	in.cursor += 1
yyFillLabel45:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel45
			}
		}
		goto yy70
	case 'l':
		goto yy149
	case 'x':
		goto yy150
	default:
		goto yy69
	}
yy111:
	in.cursor += 1
yyFillLabel46:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel46
			}
		}
		goto yy70
	case 'i':
		goto yy151
	case 'o':
		goto yy152
	case 'r':
		goto yy153
	default:
		goto yy69
	}
yy112:
	in.cursor += 1
yyFillLabel47:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel47
			}
		}
		goto yy70
	case 'l':
		goto yy154
	default:
		goto yy69
	}
yy113:
	in.cursor += 1
yyFillLabel48:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel48
			}
		}
		goto yy70
	case 'f':
		goto yy155
	case 'm':
		goto yy157
	case 'n':
		goto yy158
	case 's':
		goto yy160
	default:
		goto yy69
	}
yy114:
	in.cursor += 1
yyFillLabel49:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel49
			}
		}
		goto yy70
	case 'a':
		goto yy162
	default:
		goto yy69
	}
yy115:
	in.cursor += 1
yyFillLabel50:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel50
			}
		}
		goto yy70
	case 'o':
		goto yy163
	default:
		goto yy69
	}
yy116:
	in.cursor += 1
yyFillLabel51:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel51
			}
		}
		goto yy70
	case 'r':
		goto yy164
	default:
		goto yy69
	}
yy117:
	in.cursor += 1
yyFillLabel52:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel52
			}
		}
		goto yy70
	case 'a':
		goto yy166
	default:
		goto yy69
	}
yy118:
	in.cursor += 1
yyFillLabel53:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel53
			}
		}
		goto yy70
	case 'a':
		goto yy167
	case 'e':
		goto yy168
	default:
		goto yy69
	}
yy119:
	in.cursor += 1
yyFillLabel54:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel54
			}
		}
		goto yy70
	case 'r':
		goto yy169
	default:
		goto yy69
	}
yy120:
	in.cursor += 1
yyFillLabel55:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel55
			}
		}
		goto yy70
	case 'h':
		goto yy170
	case 'i':
		goto yy171
	default:
		goto yy69
	}
yy121:
	in.cursor += 1
yyFillLabel56:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel56
			}
		}
		goto yy70
	case 'i':
		goto yy172
	default:
		goto yy69
	}
yy122:
	in.cursor += 1
//line "py.re":181
	{ return PUNCTUATION }
//line "py.go":1584
yy123:
	in.cursor += 1
yyFillLabel57:
	yych = peek(in)
	switch (yych) {
	case '|':
		goto yy173
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel57
			}
		}
		goto yy124
	}
yy124:
//line "py.re":170
	{ return PUNCTUATION }
//line "py.go":1603
yy125:
	in.cursor += 1
//line "py.re":182
	{ return PUNCTUATION }
//line "py.go":1608
yy126:
	in.cursor += 1
//line "py.re":175
	{ return PUNCTUATION }
//line "py.go":1613
yy127:
	in.cursor += 1
//line "py.re":187
	{ return PUNCTUATION }
//line "py.go":1618
yy128:
	in.cursor += 1
yyFillLabel58:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy174
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel58
			}
		}
		goto yy129
	}
yy129:
	in.cursor = in.marker
	switch (yyaccept) {
	case 0:
		goto yy66
	case 1:
		goto yy75
	default:
		goto yy86
	}
yy130:
	in.cursor += 1
//line "py.re":171
	{ return PUNCTUATION }
//line "py.go":1648
yy131:
	in.cursor += 1
yyFillLabel59:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy175
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel59
			}
		}
		goto yy129
	}
yy132:
	in.cursor += 1
//line "py.re":192
	{ return PUNCTUATION }
//line "py.go":1668
yy133:
	in.cursor += 1
yyFillLabel60:
	yych = peek(in)
yy134:
	switch (yych) {
	case '0','1','2','3','4','5','6','7':
		goto yy133
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel60
			}
		}
		goto yy86
	}
yy135:
	in.cursor += 1
yyFillLabel61:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F':
		fallthrough
	case 'a','b','c','d','e','f':
		goto yy176
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel61
			}
		}
		goto yy129
	}
yy136:
	in.cursor += 1
//line "py.re":195
	{ return PUNCTUATION }
//line "py.go":1708
yy137:
	in.cursor += 1
//line "py.re":190
	{ return PUNCTUATION }
//line "py.go":1713
yy138:
	in.cursor += 1
//line "py.re":186
	{ return PUNCTUATION }
//line "py.go":1718
yy139:
	in.cursor += 1
//line "py.re":191
	{ return PUNCTUATION }
//line "py.go":1723
yy140:
	in.cursor += 1
yyFillLabel62:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel62
			}
		}
		goto yy70
	case 'l':
		goto yy178
	default:
		goto yy69
	}
yy141:
	in.cursor += 1
yyFillLabel63:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel63
			}
		}
		goto yy70
	case 'n':
		goto yy179
	default:
		goto yy69
	}
yy142:
	in.cursor += 1
yyFillLabel64:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel64
			}
		}
		goto yy70
	case 'u':
		goto yy180
	default:
		goto yy69
	}
yy143:
	in.cursor += 1
yyFillLabel65:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel65
			}
		}
		goto yy70
	case 'd':
		goto yy181
	default:
		goto yy69
	}
yy144:
	in.cursor += 1
yyFillLabel66:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r':
		fallthrough
	case 't','u','v','w','x','y','z':
		goto yy68
	case 's':
		goto yy183
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel66
			}
		}
		goto yy145
	}
yy145:
//line "py.re":132
	{ return KEYWORD }
//line "py.go":1822
yy146:
	in.cursor += 1
yyFillLabel67:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel67
			}
		}
		goto yy70
	case 'a':
		goto yy184
	default:
		goto yy69
	}
yy147:
	in.cursor += 1
yyFillLabel68:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel68
			}
		}
		goto yy70
	case 'n':
		goto yy185
	default:
		goto yy69
	}
yy148:
	in.cursor += 1
yyFillLabel69:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel69
			}
		}
		goto yy70
	case 'f':
		goto yy186
	case 'l':
		goto yy188
	default:
		goto yy69
	}
yy149:
	in.cursor += 1
yyFillLabel70:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel70
			}
		}
		goto yy70
	case 'i':
		goto yy190
	case 's':
		goto yy191
	default:
		goto yy69
	}
yy150:
	in.cursor += 1
yyFillLabel71:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel71
			}
		}
		goto yy70
	case 'c':
		goto yy192
	default:
		goto yy69
	}
yy151:
	in.cursor += 1
yyFillLabel72:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel72
			}
		}
		goto yy70
	case 'n':
		goto yy193
	default:
		goto yy69
	}
yy152:
	in.cursor += 1
yyFillLabel73:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel73
			}
		}
		goto yy70
	case 'r':
		goto yy194
	default:
		goto yy69
	}
yy153:
	in.cursor += 1
yyFillLabel74:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel74
			}
		}
		goto yy70
	case 'o':
		goto yy196
	default:
		goto yy69
	}
yy154:
	in.cursor += 1
yyFillLabel75:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel75
			}
		}
		goto yy70
	case 'o':
		goto yy197
	default:
		goto yy69
	}
yy155:
	in.cursor += 1
yyFillLabel76:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel76
			}
		}
		goto yy156
	}
yy156:
//line "py.re":146
	{ return KEYWORD }
//line "py.go":2006
yy157:
	in.cursor += 1
yyFillLabel77:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel77
			}
		}
		goto yy70
	case 'p':
		goto yy198
	default:
		goto yy69
	}
yy158:
	in.cursor += 1
yyFillLabel78:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel78
			}
		}
		goto yy159
	}
yy159:
//line "py.re":148
	{ return KEYWORD }
//line "py.go":2050
yy160:
	in.cursor += 1
yyFillLabel79:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel79
			}
		}
		goto yy161
	}
yy161:
//line "py.re":149
	{ return KEYWORD }
//line "py.go":2077
yy162:
	in.cursor += 1
yyFillLabel80:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel80
			}
		}
		goto yy70
	case 'm':
		goto yy199
	default:
		goto yy69
	}
yy163:
	in.cursor += 1
yyFillLabel81:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel81
			}
		}
		goto yy70
	case 'n':
		goto yy200
	case 't':
		goto yy201
	default:
		goto yy69
	}
yy164:
	in.cursor += 1
yyFillLabel82:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel82
			}
		}
		goto yy165
	}
yy165:
//line "py.re":154
	{ return KEYWORD }
//line "py.go":2140
yy166:
	in.cursor += 1
yyFillLabel83:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel83
			}
		}
		goto yy70
	case 's':
		goto yy203
	default:
		goto yy69
	}
yy167:
	in.cursor += 1
yyFillLabel84:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel84
			}
		}
		goto yy70
	case 'i':
		goto yy204
	default:
		goto yy69
	}
yy168:
	in.cursor += 1
yyFillLabel85:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel85
			}
		}
		goto yy70
	case 't':
		goto yy205
	default:
		goto yy69
	}
yy169:
	in.cursor += 1
yyFillLabel86:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel86
			}
		}
		goto yy70
	case 'y':
		goto yy206
	default:
		goto yy69
	}
yy170:
	in.cursor += 1
yyFillLabel87:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel87
			}
		}
		goto yy70
	case 'i':
		goto yy208
	default:
		goto yy69
	}
yy171:
	in.cursor += 1
yyFillLabel88:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel88
			}
		}
		goto yy70
	case 't':
		goto yy209
	default:
		goto yy69
	}
yy172:
	in.cursor += 1
yyFillLabel89:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel89
			}
		}
		goto yy70
	case 'e':
		goto yy210
	default:
		goto yy69
	}
yy173:
	in.cursor += 1
//line "py.re":172
	{ return PUNCTUATION }
//line "py.go":2264
yy174:
	in.cursor += 1
//line "py.re":127
	{ in.state = STATE_LONGSTRINGLITERAL; in.raw_str_delim = in.data[in.token:in.cursor]; return STRING }
//line "py.go":2269
yy175:
	in.cursor += 1
//line "py.re":128
	{ in.state = STATE_LONGSTRINGLITERAL; in.raw_str_delim = in.data[in.token:in.cursor]; return STRING }
//line "py.go":2274
yy176:
	in.cursor += 1
yyFillLabel90:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F':
		fallthrough
	case 'a','b','c','d','e','f':
		goto yy176
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel90
			}
		}
		goto yy177
	}
yy177:
//line "py.re":122
	{ return LITERAL }
//line "py.go":2297
yy178:
	in.cursor += 1
yyFillLabel91:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel91
			}
		}
		goto yy70
	case 's':
		goto yy211
	default:
		goto yy69
	}
yy179:
	in.cursor += 1
yyFillLabel92:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel92
			}
		}
		goto yy70
	case 'e':
		goto yy212
	default:
		goto yy69
	}
yy180:
	in.cursor += 1
yyFillLabel93:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel93
			}
		}
		goto yy70
	case 'e':
		goto yy214
	default:
		goto yy69
	}
yy181:
	in.cursor += 1
yyFillLabel94:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel94
			}
		}
		goto yy182
	}
yy182:
//line "py.re":131
	{ return KEYWORD }
//line "py.go":2375
yy183:
	in.cursor += 1
yyFillLabel95:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel95
			}
		}
		goto yy70
	case 'e':
		goto yy216
	default:
		goto yy69
	}
yy184:
	in.cursor += 1
yyFillLabel96:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel96
			}
		}
		goto yy70
	case 's':
		goto yy217
	default:
		goto yy69
	}
yy185:
	in.cursor += 1
yyFillLabel97:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel97
			}
		}
		goto yy70
	case 't':
		goto yy218
	default:
		goto yy69
	}
yy186:
	in.cursor += 1
yyFillLabel98:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel98
			}
		}
		goto yy187
	}
yy187:
//line "py.re":136
	{ return KEYWORD }
//line "py.go":2453
yy188:
	in.cursor += 1
yyFillLabel99:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel99
			}
		}
		goto yy189
	}
yy189:
//line "py.re":137
	{ return KEYWORD }
//line "py.go":2480
yy190:
	in.cursor += 1
yyFillLabel100:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel100
			}
		}
		goto yy70
	case 'f':
		goto yy219
	default:
		goto yy69
	}
yy191:
	in.cursor += 1
yyFillLabel101:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel101
			}
		}
		goto yy70
	case 'e':
		goto yy221
	default:
		goto yy69
	}
yy192:
	in.cursor += 1
yyFillLabel102:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel102
			}
		}
		goto yy70
	case 'e':
		goto yy223
	default:
		goto yy69
	}
yy193:
	in.cursor += 1
yyFillLabel103:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel103
			}
		}
		goto yy70
	case 'a':
		goto yy224
	default:
		goto yy69
	}
yy194:
	in.cursor += 1
yyFillLabel104:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel104
			}
		}
		goto yy195
	}
yy195:
//line "py.re":143
	{ return KEYWORD }
//line "py.go":2575
yy196:
	in.cursor += 1
yyFillLabel105:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel105
			}
		}
		goto yy70
	case 'm':
		goto yy225
	default:
		goto yy69
	}
yy197:
	in.cursor += 1
yyFillLabel106:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel106
			}
		}
		goto yy70
	case 'b':
		goto yy227
	default:
		goto yy69
	}
yy198:
	in.cursor += 1
yyFillLabel107:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel107
			}
		}
		goto yy70
	case 'o':
		goto yy228
	default:
		goto yy69
	}
yy199:
	in.cursor += 1
yyFillLabel108:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel108
			}
		}
		goto yy70
	case 'b':
		goto yy229
	default:
		goto yy69
	}
yy200:
	in.cursor += 1
yyFillLabel109:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel109
			}
		}
		goto yy70
	case 'l':
		goto yy230
	default:
		goto yy69
	}
yy201:
	in.cursor += 1
yyFillLabel110:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel110
			}
		}
		goto yy202
	}
yy202:
//line "py.re":153
	{ return KEYWORD }
//line "py.go":2687
yy203:
	in.cursor += 1
yyFillLabel111:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel111
			}
		}
		goto yy70
	case 's':
		goto yy231
	default:
		goto yy69
	}
yy204:
	in.cursor += 1
yyFillLabel112:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel112
			}
		}
		goto yy70
	case 's':
		goto yy233
	default:
		goto yy69
	}
yy205:
	in.cursor += 1
yyFillLabel113:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel113
			}
		}
		goto yy70
	case 'u':
		goto yy234
	default:
		goto yy69
	}
yy206:
	in.cursor += 1
yyFillLabel114:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel114
			}
		}
		goto yy207
	}
yy207:
//line "py.re":159
	{ return KEYWORD }
//line "py.go":2765
yy208:
	in.cursor += 1
yyFillLabel115:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel115
			}
		}
		goto yy70
	case 'l':
		goto yy235
	default:
		goto yy69
	}
yy209:
	in.cursor += 1
yyFillLabel116:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel116
			}
		}
		goto yy70
	case 'h':
		goto yy236
	default:
		goto yy69
	}
yy210:
	in.cursor += 1
yyFillLabel117:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel117
			}
		}
		goto yy70
	case 'l':
		goto yy238
	default:
		goto yy69
	}
yy211:
	in.cursor += 1
yyFillLabel118:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel118
			}
		}
		goto yy70
	case 'e':
		goto yy239
	default:
		goto yy69
	}
yy212:
	in.cursor += 1
yyFillLabel119:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel119
			}
		}
		goto yy213
	}
yy213:
//line "py.re":151
	{ return KEYWORD }
//line "py.go":2860
yy214:
	in.cursor += 1
yyFillLabel120:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel120
			}
		}
		goto yy215
	}
yy215:
//line "py.re":158
	{ return KEYWORD }
//line "py.go":2887
yy216:
	in.cursor += 1
yyFillLabel121:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel121
			}
		}
		goto yy70
	case 'r':
		goto yy241
	default:
		goto yy69
	}
yy217:
	in.cursor += 1
yyFillLabel122:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel122
			}
		}
		goto yy70
	case 's':
		goto yy242
	default:
		goto yy69
	}
yy218:
	in.cursor += 1
yyFillLabel123:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel123
			}
		}
		goto yy70
	case 'i':
		goto yy244
	default:
		goto yy69
	}
yy219:
	in.cursor += 1
yyFillLabel124:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel124
			}
		}
		goto yy220
	}
yy220:
//line "py.re":138
	{ return KEYWORD }
//line "py.go":2965
yy221:
	in.cursor += 1
yyFillLabel125:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel125
			}
		}
		goto yy222
	}
yy222:
//line "py.re":139
	{ return KEYWORD }
//line "py.go":2992
yy223:
	in.cursor += 1
yyFillLabel126:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel126
			}
		}
		goto yy70
	case 'p':
		goto yy245
	default:
		goto yy69
	}
yy224:
	in.cursor += 1
yyFillLabel127:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel127
			}
		}
		goto yy70
	case 'l':
		goto yy246
	default:
		goto yy69
	}
yy225:
	in.cursor += 1
yyFillLabel128:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel128
			}
		}
		goto yy226
	}
yy226:
//line "py.re":144
	{ return KEYWORD }
//line "py.go":3053
yy227:
	in.cursor += 1
yyFillLabel129:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel129
			}
		}
		goto yy70
	case 'a':
		goto yy247
	default:
		goto yy69
	}
yy228:
	in.cursor += 1
yyFillLabel130:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel130
			}
		}
		goto yy70
	case 'r':
		goto yy248
	default:
		goto yy69
	}
yy229:
	in.cursor += 1
yyFillLabel131:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel131
			}
		}
		goto yy70
	case 'd':
		goto yy249
	default:
		goto yy69
	}
yy230:
	in.cursor += 1
yyFillLabel132:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel132
			}
		}
		goto yy70
	case 'o':
		goto yy250
	default:
		goto yy69
	}
yy231:
	in.cursor += 1
yyFillLabel133:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel133
			}
		}
		goto yy232
	}
yy232:
//line "py.re":155
	{ return KEYWORD }
//line "py.go":3148
yy233:
	in.cursor += 1
yyFillLabel134:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel134
			}
		}
		goto yy70
	case 'e':
		goto yy251
	default:
		goto yy69
	}
yy234:
	in.cursor += 1
yyFillLabel135:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel135
			}
		}
		goto yy70
	case 'r':
		goto yy253
	default:
		goto yy69
	}
yy235:
	in.cursor += 1
yyFillLabel136:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel136
			}
		}
		goto yy70
	case 'e':
		goto yy254
	default:
		goto yy69
	}
yy236:
	in.cursor += 1
yyFillLabel137:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel137
			}
		}
		goto yy237
	}
yy237:
//line "py.re":161
	{ return KEYWORD }
//line "py.go":3226
yy238:
	in.cursor += 1
yyFillLabel138:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel138
			}
		}
		goto yy70
	case 'd':
		goto yy256
	default:
		goto yy69
	}
yy239:
	in.cursor += 1
yyFillLabel139:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel139
			}
		}
		goto yy240
	}
yy240:
//line "py.re":141
	{ return KEYWORD }
//line "py.go":3270
yy241:
	in.cursor += 1
yyFillLabel140:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel140
			}
		}
		goto yy70
	case 't':
		goto yy258
	default:
		goto yy69
	}
yy242:
	in.cursor += 1
yyFillLabel141:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel141
			}
		}
		goto yy243
	}
yy243:
//line "py.re":134
	{ return KEYWORD }
//line "py.go":3314
yy244:
	in.cursor += 1
yyFillLabel142:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel142
			}
		}
		goto yy70
	case 'n':
		goto yy260
	default:
		goto yy69
	}
yy245:
	in.cursor += 1
yyFillLabel143:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel143
			}
		}
		goto yy70
	case 't':
		goto yy261
	default:
		goto yy69
	}
yy246:
	in.cursor += 1
yyFillLabel144:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel144
			}
		}
		goto yy70
	case 'l':
		goto yy263
	default:
		goto yy69
	}
yy247:
	in.cursor += 1
yyFillLabel145:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel145
			}
		}
		goto yy70
	case 'l':
		goto yy264
	default:
		goto yy69
	}
yy248:
	in.cursor += 1
yyFillLabel146:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel146
			}
		}
		goto yy70
	case 't':
		goto yy266
	default:
		goto yy69
	}
yy249:
	in.cursor += 1
yyFillLabel147:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel147
			}
		}
		goto yy70
	case 'a':
		goto yy268
	default:
		goto yy69
	}
yy250:
	in.cursor += 1
yyFillLabel148:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel148
			}
		}
		goto yy70
	case 'c':
		goto yy270
	default:
		goto yy69
	}
yy251:
	in.cursor += 1
yyFillLabel149:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel149
			}
		}
		goto yy252
	}
yy252:
//line "py.re":156
	{ return KEYWORD }
//line "py.go":3460
yy253:
	in.cursor += 1
yyFillLabel150:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel150
			}
		}
		goto yy70
	case 'n':
		goto yy271
	default:
		goto yy69
	}
yy254:
	in.cursor += 1
yyFillLabel151:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel151
			}
		}
		goto yy255
	}
yy255:
//line "py.re":160
	{ return KEYWORD }
//line "py.go":3504
yy256:
	in.cursor += 1
yyFillLabel152:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel152
			}
		}
		goto yy257
	}
yy257:
//line "py.re":162
	{ return KEYWORD }
//line "py.go":3531
yy258:
	in.cursor += 1
yyFillLabel153:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel153
			}
		}
		goto yy259
	}
yy259:
//line "py.re":133
	{ return KEYWORD }
//line "py.go":3558
yy260:
	in.cursor += 1
yyFillLabel154:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel154
			}
		}
		goto yy70
	case 'u':
		goto yy273
	default:
		goto yy69
	}
yy261:
	in.cursor += 1
yyFillLabel155:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel155
			}
		}
		goto yy262
	}
yy262:
//line "py.re":140
	{ return KEYWORD }
//line "py.go":3602
yy263:
	in.cursor += 1
yyFillLabel156:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel156
			}
		}
		goto yy70
	case 'y':
		goto yy274
	default:
		goto yy69
	}
yy264:
	in.cursor += 1
yyFillLabel157:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel157
			}
		}
		goto yy265
	}
yy265:
//line "py.re":145
	{ return KEYWORD }
//line "py.go":3646
yy266:
	in.cursor += 1
yyFillLabel158:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel158
			}
		}
		goto yy267
	}
yy267:
//line "py.re":147
	{ return KEYWORD }
//line "py.go":3673
yy268:
	in.cursor += 1
yyFillLabel159:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel159
			}
		}
		goto yy269
	}
yy269:
//line "py.re":150
	{ return KEYWORD }
//line "py.go":3700
yy270:
	in.cursor += 1
yyFillLabel160:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel160
			}
		}
		goto yy70
	case 'a':
		goto yy276
	default:
		goto yy69
	}
yy271:
	in.cursor += 1
yyFillLabel161:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel161
			}
		}
		goto yy272
	}
yy272:
//line "py.re":157
	{ return KEYWORD }
//line "py.go":3744
yy273:
	in.cursor += 1
yyFillLabel162:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel162
			}
		}
		goto yy70
	case 'e':
		goto yy277
	default:
		goto yy69
	}
yy274:
	in.cursor += 1
yyFillLabel163:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel163
			}
		}
		goto yy275
	}
yy275:
//line "py.re":142
	{ return KEYWORD }
//line "py.go":3788
yy276:
	in.cursor += 1
yyFillLabel164:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel164
			}
		}
		goto yy70
	case 'l':
		goto yy279
	default:
		goto yy69
	}
yy277:
	in.cursor += 1
yyFillLabel165:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel165
			}
		}
		goto yy278
	}
yy278:
//line "py.re":135
	{ return KEYWORD }
//line "py.go":3832
yy279:
	in.cursor += 1
yyFillLabel166:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy68
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel166
			}
		}
		goto yy280
	}
yy280:
//line "py.re":152
	{ return KEYWORD }
//line "py.go":3859
yy281:
//line "py.re":113
	{ return END }
//line "py.go":3863
}
//line "py.re":199

    }
}

func init() {
	register([]string{".py"}, py_lex)
}