// Code generated by re2c 3.0, DO NOT EDIT.
//line "py.re":1
package golexers

//line "word.re":1
//line "unicode_categories.re":1
//line "unicode_categories.re":40

//line "word.re":1

//line "word.re":8
//line "py.re":3


import (
	"bytes"
    "fmt"
)

//line "py.re":19


func py_lex_str(in *Input) TokenType {
	for {
		in.token = in.cursor
    
//line "py.go":28
{
	var yych byte
yyFillLabel0:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy3
	case '\'':
		goto yy4
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy5
	case '\\':
		goto yy7
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel0
			}
			goto yy19
		}
		goto yy1
	}
yy1:
	in.cursor += 1
yy2:
//line "py.re":25
	{ return STRING }
//line "py.go":62
yy3:
	in.cursor += 1
//line "py.re":27
	{ if in.state == STATE_STRINGLITERAL { in.state = STATE_NORMAL }; return STRING }
//line "py.go":67
yy4:
	in.cursor += 1
//line "py.re":28
	{ if in.state == STATE_CHARLITERAL { in.state = STATE_NORMAL }; return STRING }
//line "py.go":72
yy5:
	in.cursor += 1
yyFillLabel1:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy5
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel1
			}
		}
		goto yy6
	}
yy6:
//line "py.re":29
	{ return STRINGWORD }
//line "py.go":97
yy7:
	in.cursor += 1
yyFillLabel2:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy8
	case '\'':
		goto yy9
	case '?':
		goto yy10
	case '\\':
		goto yy11
	case 'a':
		goto yy12
	case 'b':
		goto yy13
	case 'f':
		goto yy14
	case 'n':
		goto yy15
	case 'r':
		goto yy16
	case 't':
		goto yy17
	case 'v':
		goto yy18
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel2
			}
		}
		goto yy2
	}
yy8:
	in.cursor += 1
//line "py.re":39
	{ return STRING }
//line "py.go":137
yy9:
	in.cursor += 1
//line "py.re":38
	{ return STRING }
//line "py.go":142
yy10:
	in.cursor += 1
//line "py.re":40
	{ return STRING }
//line "py.go":147
yy11:
	in.cursor += 1
//line "py.re":37
	{ return STRING }
//line "py.go":152
yy12:
	in.cursor += 1
//line "py.re":30
	{ return STRING }
//line "py.go":157
yy13:
	in.cursor += 1
//line "py.re":31
	{ return STRING }
//line "py.go":162
yy14:
	in.cursor += 1
//line "py.re":32
	{ return STRING }
//line "py.go":167
yy15:
	in.cursor += 1
//line "py.re":33
	{ return STRING }
//line "py.go":172
yy16:
	in.cursor += 1
//line "py.re":34
	{ return STRING }
//line "py.go":177
yy17:
	in.cursor += 1
//line "py.re":35
	{ return STRING }
//line "py.go":182
yy18:
	in.cursor += 1
//line "py.re":36
	{ return STRING }
//line "py.go":187
yy19:
//line "py.re":26
	{ return -1 }
//line "py.go":191
}
//line "py.re":45

	}
}

func py_lex_long_str(in *Input, start bool) TokenType {
	for {
		if start {
			in.raw_str_delim = in.data[in.token + 2:in.cursor - 1]
			start = false
		}
		in.token = in.cursor
    
//line "py.go":206
{
	var yych byte
yyFillLabel3:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy23
	case '\n':
		goto yy25
	case '"':
		goto yy26
	case '\'':
		goto yy27
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy28
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel3
			}
			goto yy35
		}
		goto yy21
	}
yy21:
	in.cursor += 1
yy22:
//line "py.re":57
	{ return STRING }
//line "py.go":246
yy23:
	in.cursor += 1
yyFillLabel4:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy23
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel4
			}
		}
		goto yy24
	}
yy24:
//line "py.re":60
	{ continue }
//line "py.go":269
yy25:
	in.cursor += 1
//line "py.re":59
	{ in.bolcursor = in.cursor; in.line += 1; continue }
//line "py.go":274
yy26:
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel5:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy30
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel5
			}
		}
		goto yy22
	}
yy27:
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel6:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy32
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel6
			}
		}
		goto yy22
	}
yy28:
	in.cursor += 1
yyFillLabel7:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy28
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel7
			}
		}
		goto yy29
	}
yy29:
//line "py.re":65
	{ return STRINGWORD }
//line "py.go":331
yy30:
	in.cursor += 1
yyFillLabel8:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy33
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel8
			}
		}
		goto yy31
	}
yy31:
	in.cursor = in.marker
	goto yy22
yy32:
	in.cursor += 1
yyFillLabel9:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy34
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel9
			}
		}
		goto yy31
	}
yy33:
	in.cursor += 1
//line "py.re":62
	{ if bytes.Equal(in.raw_str_delim, in.data[in.token:in.cursor]) { in.state = STATE_NORMAL; in.raw_str_delim = nil }; return STRING }
//line "py.go":369
yy34:
	in.cursor += 1
//line "py.re":63
	{ if bytes.Equal(in.raw_str_delim, in.data[in.token:in.cursor]) { in.state = STATE_NORMAL; in.raw_str_delim = nil }; return STRING }
//line "py.go":374
yy35:
//line "py.re":58
	{ return -1 }
//line "py.go":378
}
//line "py.re":66

	}
}

func py_lex(in *Input) TokenType {
	for {
		in.token = in.cursor
        //fmt.Printf("start at %d\n", in.token)
		if in.state == STATE_STRINGLITERAL || in.state == STATE_CHARLITERAL {
			t := py_lex_str(in)
			if t >= 0 {
				return t
			}
		} else if (in.state == STATE_LONGSTRINGLITERAL) {
			t := py_lex_long_str(in, false)
			if t >= 0 {
				return t
			}
		} else if (in.state == STATE_EOLCOMMENT) {
			t := lex_eol_comment(in)
			if t >= 0 {
				return t
			}
		}

    
//line "py.go":407
{
	var yych byte
	yyaccept := 0
yyFillLabel10:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy38
	case '\n':
		goto yy40
	case '!':
		goto yy41
	case '"':
		goto yy43
	case '#':
		goto yy45
	case '$':
		fallthrough
	case 'A','B','C','D','E':
		fallthrough
	case 'G','H','I','J','K','L','M':
		fallthrough
	case 'O','P','Q','R','S':
		fallthrough
	case 'U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'b':
		fallthrough
	case 'h':
		fallthrough
	case 'j','k':
		fallthrough
	case 'm':
		fallthrough
	case 'q':
		fallthrough
	case 's':
		fallthrough
	case 'u','v':
		fallthrough
	case 'x':
		fallthrough
	case 'z':
		goto yy46
	case '%':
		goto yy49
	case '&':
		goto yy50
	case '\'':
		goto yy52
	case '(':
		goto yy54
	case ')':
		goto yy55
	case '*':
		goto yy56
	case '+':
		goto yy57
	case ',':
		goto yy58
	case '-':
		goto yy59
	case '.':
		goto yy61
	case '/':
		goto yy62
	case '0':
		goto yy63
	case '1','2','3','4','5','6','7','8','9':
		goto yy65
	case ':':
		goto yy67
	case ';':
		goto yy69
	case '<':
		goto yy70
	case '=':
		goto yy72
	case '>':
		goto yy74
	case '?':
		goto yy76
	case '@':
		goto yy77
	case 'F':
		goto yy78
	case 'N':
		goto yy79
	case 'T':
		goto yy80
	case '[':
		goto yy81
	case '\\':
		goto yy82
	case ']':
		goto yy83
	case '^':
		goto yy84
	case 'a':
		goto yy85
	case 'c':
		goto yy86
	case 'd':
		goto yy87
	case 'e':
		goto yy88
	case 'f':
		goto yy89
	case 'g':
		goto yy90
	case 'i':
		goto yy91
	case 'l':
		goto yy92
	case 'n':
		goto yy93
	case 'o':
		goto yy94
	case 'p':
		goto yy95
	case 'r':
		goto yy96
	case 't':
		goto yy97
	case 'w':
		goto yy98
	case 'y':
		goto yy99
	case '{':
		goto yy100
	case '|':
		goto yy101
	case '}':
		goto yy103
	case '~':
		goto yy104
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel10
			}
			goto yy259
		}
		goto yy37
	}
yy37:
	in.cursor += 1
//line "py.re":96
	{ fmt.Printf("%s: %d: match %2x\n", in.filename, in.line, in.data[in.cursor-1]); continue }
//line "py.go":563
yy38:
	in.cursor += 1
yyFillLabel11:
	yych = peek(in)
	switch (yych) {
	case '\t':
		fallthrough
	case '\v','\f','\r':
		fallthrough
	case ' ':
		goto yy38
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel11
			}
		}
		goto yy39
	}
yy39:
//line "py.re":93
	{ continue }
//line "py.go":586
yy40:
	in.cursor += 1
//line "py.re":94
	{ in.bolcursor = in.cursor; in.line += 1; continue }
//line "py.go":591
yy41:
	in.cursor += 1
yyFillLabel12:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy105
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel12
			}
		}
		goto yy42
	}
yy42:
//line "py.re":157
	{ return PUNCTUATION }
//line "py.go":610
yy43:
	yyaccept = 0
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel13:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy106
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel13
			}
		}
		goto yy44
	}
yy44:
//line "py.re":109
	{ in.state = STATE_STRINGLITERAL; return STRING }
//line "py.go":631
yy45:
	in.cursor += 1
//line "py.re":113
	{ in.state = STATE_EOLCOMMENT; return COMMENT }
//line "py.go":636
yy46:
	in.cursor += 1
yyFillLabel14:
	yych = peek(in)
yy47:
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel14
			}
		}
		goto yy48
	}
yy48:
//line "py.re":181
	{ return IDENTIFIER }
//line "py.go":664
yy49:
	in.cursor += 1
//line "py.re":152
	{ return PUNCTUATION }
//line "py.go":669
yy50:
	in.cursor += 1
yyFillLabel15:
	yych = peek(in)
	switch (yych) {
	case '&':
		goto yy108
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel15
			}
		}
		goto yy51
	}
yy51:
//line "py.re":153
	{ return PUNCTUATION }
//line "py.go":688
yy52:
	yyaccept = 1
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel16:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy109
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel16
			}
		}
		goto yy53
	}
yy53:
//line "py.re":110
	{ in.state = STATE_CHARLITERAL; return STRING }
//line "py.go":709
yy54:
	in.cursor += 1
//line "py.re":163
	{ return PUNCTUATION }
//line "py.go":714
yy55:
	in.cursor += 1
//line "py.re":164
	{ return PUNCTUATION }
//line "py.go":719
yy56:
	in.cursor += 1
//line "py.re":151
	{ return PUNCTUATION }
//line "py.go":724
yy57:
	in.cursor += 1
//line "py.re":148
	{ return PUNCTUATION }
//line "py.go":729
yy58:
	in.cursor += 1
//line "py.re":162
	{ return PUNCTUATION }
//line "py.go":734
yy59:
	in.cursor += 1
yyFillLabel17:
	yych = peek(in)
	switch (yych) {
	case '>':
		goto yy110
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel17
			}
		}
		goto yy60
	}
yy60:
//line "py.re":149
	{ return PUNCTUATION }
//line "py.go":753
yy61:
	in.cursor += 1
//line "py.re":161
	{ return PUNCTUATION }
//line "py.go":758
yy62:
	in.cursor += 1
//line "py.re":150
	{ return PUNCTUATION }
//line "py.go":763
yy63:
	yyaccept = 2
	in.cursor += 1
	in.marker = in.cursor
yyFillLabel18:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel18
			}
		}
		goto yy64
	case 'x':
		goto yy113
	default:
		goto yy112
	}
yy64:
//line "py.re":107
	{ return LITERAL }
//line "py.go":786
yy65:
	in.cursor += 1
yyFillLabel19:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		goto yy65
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel19
			}
		}
		goto yy66
	}
yy66:
//line "py.re":105
	{ return LITERAL }
//line "py.go":805
yy67:
	in.cursor += 1
yyFillLabel20:
	yych = peek(in)
	switch (yych) {
	case ':':
		goto yy114
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel20
			}
		}
		goto yy68
	}
yy68:
//line "py.re":178
	{ return PUNCTUATION }
//line "py.go":824
yy69:
	in.cursor += 1
//line "py.re":160
	{ return PUNCTUATION }
//line "py.go":829
yy70:
	in.cursor += 1
yyFillLabel21:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy115
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel21
			}
		}
		goto yy71
	}
yy71:
//line "py.re":172
	{ return PUNCTUATION }
//line "py.go":848
yy72:
	in.cursor += 1
yyFillLabel22:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy116
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel22
			}
		}
		goto yy73
	}
yy73:
//line "py.re":169
	{ return PUNCTUATION }
//line "py.go":867
yy74:
	in.cursor += 1
yyFillLabel23:
	yych = peek(in)
	switch (yych) {
	case '=':
		goto yy117
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel23
			}
		}
		goto yy75
	}
yy75:
//line "py.re":173
	{ return PUNCTUATION }
//line "py.go":886
yy76:
	in.cursor += 1
//line "py.re":177
	{ return PUNCTUATION }
//line "py.go":891
yy77:
	in.cursor += 1
//line "py.re":99
	{ continue }
//line "py.go":896
yy78:
	in.cursor += 1
yyFillLabel24:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel24
			}
		}
		goto yy48
	case 'a':
		goto yy118
	default:
		goto yy47
	}
yy79:
	in.cursor += 1
yyFillLabel25:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel25
			}
		}
		goto yy48
	case 'o':
		goto yy119
	default:
		goto yy47
	}
yy80:
	in.cursor += 1
yyFillLabel26:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel26
			}
		}
		goto yy48
	case 'r':
		goto yy120
	default:
		goto yy47
	}
yy81:
	in.cursor += 1
//line "py.re":167
	{ return PUNCTUATION }
//line "py.go":952
yy82:
	in.cursor += 1
//line "py.re":92
	{ continue }
//line "py.go":957
yy83:
	in.cursor += 1
//line "py.re":168
	{ return PUNCTUATION }
//line "py.go":962
yy84:
	in.cursor += 1
//line "py.re":158
	{ return PUNCTUATION }
//line "py.go":967
yy85:
	in.cursor += 1
yyFillLabel27:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel27
			}
		}
		goto yy48
	case 'n':
		goto yy121
	case 's':
		goto yy122
	default:
		goto yy47
	}
yy86:
	in.cursor += 1
yyFillLabel28:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel28
			}
		}
		goto yy48
	case 'l':
		goto yy124
	case 'o':
		goto yy125
	default:
		goto yy47
	}
yy87:
	in.cursor += 1
yyFillLabel29:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel29
			}
		}
		goto yy48
	case 'e':
		goto yy126
	default:
		goto yy47
	}
yy88:
	in.cursor += 1
yyFillLabel30:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel30
			}
		}
		goto yy48
	case 'l':
		goto yy127
	case 'x':
		goto yy128
	default:
		goto yy47
	}
yy89:
	in.cursor += 1
yyFillLabel31:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel31
			}
		}
		goto yy48
	case 'i':
		goto yy129
	case 'o':
		goto yy130
	case 'r':
		goto yy131
	default:
		goto yy47
	}
yy90:
	in.cursor += 1
yyFillLabel32:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel32
			}
		}
		goto yy48
	case 'l':
		goto yy132
	default:
		goto yy47
	}
yy91:
	in.cursor += 1
yyFillLabel33:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel33
			}
		}
		goto yy48
	case 'f':
		goto yy133
	case 'm':
		goto yy135
	case 'n':
		goto yy136
	case 's':
		goto yy138
	default:
		goto yy47
	}
yy92:
	in.cursor += 1
yyFillLabel34:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel34
			}
		}
		goto yy48
	case 'a':
		goto yy140
	default:
		goto yy47
	}
yy93:
	in.cursor += 1
yyFillLabel35:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel35
			}
		}
		goto yy48
	case 'o':
		goto yy141
	default:
		goto yy47
	}
yy94:
	in.cursor += 1
yyFillLabel36:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel36
			}
		}
		goto yy48
	case 'r':
		goto yy142
	default:
		goto yy47
	}
yy95:
	in.cursor += 1
yyFillLabel37:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel37
			}
		}
		goto yy48
	case 'a':
		goto yy144
	default:
		goto yy47
	}
yy96:
	in.cursor += 1
yyFillLabel38:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel38
			}
		}
		goto yy48
	case 'a':
		goto yy145
	case 'e':
		goto yy146
	default:
		goto yy47
	}
yy97:
	in.cursor += 1
yyFillLabel39:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel39
			}
		}
		goto yy48
	case 'r':
		goto yy147
	default:
		goto yy47
	}
yy98:
	in.cursor += 1
yyFillLabel40:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel40
			}
		}
		goto yy48
	case 'h':
		goto yy148
	case 'i':
		goto yy149
	default:
		goto yy47
	}
yy99:
	in.cursor += 1
yyFillLabel41:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel41
			}
		}
		goto yy48
	case 'i':
		goto yy150
	default:
		goto yy47
	}
yy100:
	in.cursor += 1
//line "py.re":165
	{ return PUNCTUATION }
//line "py.go":1247
yy101:
	in.cursor += 1
yyFillLabel42:
	yych = peek(in)
	switch (yych) {
	case '|':
		goto yy151
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel42
			}
		}
		goto yy102
	}
yy102:
//line "py.re":154
	{ return PUNCTUATION }
//line "py.go":1266
yy103:
	in.cursor += 1
//line "py.re":166
	{ return PUNCTUATION }
//line "py.go":1271
yy104:
	in.cursor += 1
//line "py.re":159
	{ return PUNCTUATION }
//line "py.go":1276
yy105:
	in.cursor += 1
//line "py.re":171
	{ return PUNCTUATION }
//line "py.go":1281
yy106:
	in.cursor += 1
yyFillLabel43:
	yych = peek(in)
	switch (yych) {
	case '"':
		goto yy152
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel43
			}
		}
		goto yy107
	}
yy107:
	in.cursor = in.marker
	switch (yyaccept) {
	case 0:
		goto yy44
	case 1:
		goto yy53
	default:
		goto yy64
	}
yy108:
	in.cursor += 1
//line "py.re":155
	{ return PUNCTUATION }
//line "py.go":1311
yy109:
	in.cursor += 1
yyFillLabel44:
	yych = peek(in)
	switch (yych) {
	case '\'':
		goto yy153
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel44
			}
		}
		goto yy107
	}
yy110:
	in.cursor += 1
//line "py.re":176
	{ return PUNCTUATION }
//line "py.go":1331
yy111:
	in.cursor += 1
yyFillLabel45:
	yych = peek(in)
yy112:
	switch (yych) {
	case '0','1','2','3','4','5','6','7':
		goto yy111
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel45
			}
		}
		goto yy64
	}
yy113:
	in.cursor += 1
yyFillLabel46:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F':
		fallthrough
	case 'a','b','c','d','e','f':
		goto yy154
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel46
			}
		}
		goto yy107
	}
yy114:
	in.cursor += 1
//line "py.re":179
	{ return PUNCTUATION }
//line "py.go":1371
yy115:
	in.cursor += 1
//line "py.re":174
	{ return PUNCTUATION }
//line "py.go":1376
yy116:
	in.cursor += 1
//line "py.re":170
	{ return PUNCTUATION }
//line "py.go":1381
yy117:
	in.cursor += 1
//line "py.re":175
	{ return PUNCTUATION }
//line "py.go":1386
yy118:
	in.cursor += 1
yyFillLabel47:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel47
			}
		}
		goto yy48
	case 'l':
		goto yy156
	default:
		goto yy47
	}
yy119:
	in.cursor += 1
yyFillLabel48:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel48
			}
		}
		goto yy48
	case 'n':
		goto yy157
	default:
		goto yy47
	}
yy120:
	in.cursor += 1
yyFillLabel49:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel49
			}
		}
		goto yy48
	case 'u':
		goto yy158
	default:
		goto yy47
	}
yy121:
	in.cursor += 1
yyFillLabel50:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel50
			}
		}
		goto yy48
	case 'd':
		goto yy159
	default:
		goto yy47
	}
yy122:
	in.cursor += 1
yyFillLabel51:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r':
		fallthrough
	case 't','u','v','w','x','y','z':
		goto yy46
	case 's':
		goto yy161
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel51
			}
		}
		goto yy123
	}
yy123:
//line "py.re":116
	{ return KEYWORD }
//line "py.go":1485
yy124:
	in.cursor += 1
yyFillLabel52:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel52
			}
		}
		goto yy48
	case 'a':
		goto yy162
	default:
		goto yy47
	}
yy125:
	in.cursor += 1
yyFillLabel53:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel53
			}
		}
		goto yy48
	case 'n':
		goto yy163
	default:
		goto yy47
	}
yy126:
	in.cursor += 1
yyFillLabel54:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel54
			}
		}
		goto yy48
	case 'f':
		goto yy164
	case 'l':
		goto yy166
	default:
		goto yy47
	}
yy127:
	in.cursor += 1
yyFillLabel55:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel55
			}
		}
		goto yy48
	case 'i':
		goto yy168
	case 's':
		goto yy169
	default:
		goto yy47
	}
yy128:
	in.cursor += 1
yyFillLabel56:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel56
			}
		}
		goto yy48
	case 'c':
		goto yy170
	default:
		goto yy47
	}
yy129:
	in.cursor += 1
yyFillLabel57:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel57
			}
		}
		goto yy48
	case 'n':
		goto yy171
	default:
		goto yy47
	}
yy130:
	in.cursor += 1
yyFillLabel58:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel58
			}
		}
		goto yy48
	case 'r':
		goto yy172
	default:
		goto yy47
	}
yy131:
	in.cursor += 1
yyFillLabel59:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel59
			}
		}
		goto yy48
	case 'o':
		goto yy174
	default:
		goto yy47
	}
yy132:
	in.cursor += 1
yyFillLabel60:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel60
			}
		}
		goto yy48
	case 'o':
		goto yy175
	default:
		goto yy47
	}
yy133:
	in.cursor += 1
yyFillLabel61:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel61
			}
		}
		goto yy134
	}
yy134:
//line "py.re":130
	{ return KEYWORD }
//line "py.go":1669
yy135:
	in.cursor += 1
yyFillLabel62:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel62
			}
		}
		goto yy48
	case 'p':
		goto yy176
	default:
		goto yy47
	}
yy136:
	in.cursor += 1
yyFillLabel63:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel63
			}
		}
		goto yy137
	}
yy137:
//line "py.re":132
	{ return KEYWORD }
//line "py.go":1713
yy138:
	in.cursor += 1
yyFillLabel64:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel64
			}
		}
		goto yy139
	}
yy139:
//line "py.re":133
	{ return KEYWORD }
//line "py.go":1740
yy140:
	in.cursor += 1
yyFillLabel65:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel65
			}
		}
		goto yy48
	case 'm':
		goto yy177
	default:
		goto yy47
	}
yy141:
	in.cursor += 1
yyFillLabel66:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel66
			}
		}
		goto yy48
	case 'n':
		goto yy178
	case 't':
		goto yy179
	default:
		goto yy47
	}
yy142:
	in.cursor += 1
yyFillLabel67:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel67
			}
		}
		goto yy143
	}
yy143:
//line "py.re":138
	{ return KEYWORD }
//line "py.go":1803
yy144:
	in.cursor += 1
yyFillLabel68:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel68
			}
		}
		goto yy48
	case 's':
		goto yy181
	default:
		goto yy47
	}
yy145:
	in.cursor += 1
yyFillLabel69:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel69
			}
		}
		goto yy48
	case 'i':
		goto yy182
	default:
		goto yy47
	}
yy146:
	in.cursor += 1
yyFillLabel70:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel70
			}
		}
		goto yy48
	case 't':
		goto yy183
	default:
		goto yy47
	}
yy147:
	in.cursor += 1
yyFillLabel71:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel71
			}
		}
		goto yy48
	case 'y':
		goto yy184
	default:
		goto yy47
	}
yy148:
	in.cursor += 1
yyFillLabel72:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel72
			}
		}
		goto yy48
	case 'i':
		goto yy186
	default:
		goto yy47
	}
yy149:
	in.cursor += 1
yyFillLabel73:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel73
			}
		}
		goto yy48
	case 't':
		goto yy187
	default:
		goto yy47
	}
yy150:
	in.cursor += 1
yyFillLabel74:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel74
			}
		}
		goto yy48
	case 'e':
		goto yy188
	default:
		goto yy47
	}
yy151:
	in.cursor += 1
//line "py.re":156
	{ return PUNCTUATION }
//line "py.go":1927
yy152:
	in.cursor += 1
//line "py.re":111
	{ in.state = STATE_LONGSTRINGLITERAL; in.raw_str_delim = in.data[in.token:in.cursor]; return STRING }
//line "py.go":1932
yy153:
	in.cursor += 1
//line "py.re":112
	{ in.state = STATE_LONGSTRINGLITERAL; in.raw_str_delim = in.data[in.token:in.cursor]; return STRING }
//line "py.go":1937
yy154:
	in.cursor += 1
yyFillLabel75:
	yych = peek(in)
	switch (yych) {
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F':
		fallthrough
	case 'a','b','c','d','e','f':
		goto yy154
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel75
			}
		}
		goto yy155
	}
yy155:
//line "py.re":106
	{ return LITERAL }
//line "py.go":1960
yy156:
	in.cursor += 1
yyFillLabel76:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel76
			}
		}
		goto yy48
	case 's':
		goto yy189
	default:
		goto yy47
	}
yy157:
	in.cursor += 1
yyFillLabel77:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel77
			}
		}
		goto yy48
	case 'e':
		goto yy190
	default:
		goto yy47
	}
yy158:
	in.cursor += 1
yyFillLabel78:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel78
			}
		}
		goto yy48
	case 'e':
		goto yy192
	default:
		goto yy47
	}
yy159:
	in.cursor += 1
yyFillLabel79:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel79
			}
		}
		goto yy160
	}
yy160:
//line "py.re":115
	{ return KEYWORD }
//line "py.go":2038
yy161:
	in.cursor += 1
yyFillLabel80:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel80
			}
		}
		goto yy48
	case 'e':
		goto yy194
	default:
		goto yy47
	}
yy162:
	in.cursor += 1
yyFillLabel81:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel81
			}
		}
		goto yy48
	case 's':
		goto yy195
	default:
		goto yy47
	}
yy163:
	in.cursor += 1
yyFillLabel82:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel82
			}
		}
		goto yy48
	case 't':
		goto yy196
	default:
		goto yy47
	}
yy164:
	in.cursor += 1
yyFillLabel83:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel83
			}
		}
		goto yy165
	}
yy165:
//line "py.re":120
	{ return KEYWORD }
//line "py.go":2116
yy166:
	in.cursor += 1
yyFillLabel84:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel84
			}
		}
		goto yy167
	}
yy167:
//line "py.re":121
	{ return KEYWORD }
//line "py.go":2143
yy168:
	in.cursor += 1
yyFillLabel85:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel85
			}
		}
		goto yy48
	case 'f':
		goto yy197
	default:
		goto yy47
	}
yy169:
	in.cursor += 1
yyFillLabel86:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel86
			}
		}
		goto yy48
	case 'e':
		goto yy199
	default:
		goto yy47
	}
yy170:
	in.cursor += 1
yyFillLabel87:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel87
			}
		}
		goto yy48
	case 'e':
		goto yy201
	default:
		goto yy47
	}
yy171:
	in.cursor += 1
yyFillLabel88:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel88
			}
		}
		goto yy48
	case 'a':
		goto yy202
	default:
		goto yy47
	}
yy172:
	in.cursor += 1
yyFillLabel89:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel89
			}
		}
		goto yy173
	}
yy173:
//line "py.re":127
	{ return KEYWORD }
//line "py.go":2238
yy174:
	in.cursor += 1
yyFillLabel90:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel90
			}
		}
		goto yy48
	case 'm':
		goto yy203
	default:
		goto yy47
	}
yy175:
	in.cursor += 1
yyFillLabel91:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel91
			}
		}
		goto yy48
	case 'b':
		goto yy205
	default:
		goto yy47
	}
yy176:
	in.cursor += 1
yyFillLabel92:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel92
			}
		}
		goto yy48
	case 'o':
		goto yy206
	default:
		goto yy47
	}
yy177:
	in.cursor += 1
yyFillLabel93:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel93
			}
		}
		goto yy48
	case 'b':
		goto yy207
	default:
		goto yy47
	}
yy178:
	in.cursor += 1
yyFillLabel94:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel94
			}
		}
		goto yy48
	case 'l':
		goto yy208
	default:
		goto yy47
	}
yy179:
	in.cursor += 1
yyFillLabel95:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel95
			}
		}
		goto yy180
	}
yy180:
//line "py.re":137
	{ return KEYWORD }
//line "py.go":2350
yy181:
	in.cursor += 1
yyFillLabel96:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel96
			}
		}
		goto yy48
	case 's':
		goto yy209
	default:
		goto yy47
	}
yy182:
	in.cursor += 1
yyFillLabel97:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel97
			}
		}
		goto yy48
	case 's':
		goto yy211
	default:
		goto yy47
	}
yy183:
	in.cursor += 1
yyFillLabel98:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel98
			}
		}
		goto yy48
	case 'u':
		goto yy212
	default:
		goto yy47
	}
yy184:
	in.cursor += 1
yyFillLabel99:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel99
			}
		}
		goto yy185
	}
yy185:
//line "py.re":143
	{ return KEYWORD }
//line "py.go":2428
yy186:
	in.cursor += 1
yyFillLabel100:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel100
			}
		}
		goto yy48
	case 'l':
		goto yy213
	default:
		goto yy47
	}
yy187:
	in.cursor += 1
yyFillLabel101:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel101
			}
		}
		goto yy48
	case 'h':
		goto yy214
	default:
		goto yy47
	}
yy188:
	in.cursor += 1
yyFillLabel102:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel102
			}
		}
		goto yy48
	case 'l':
		goto yy216
	default:
		goto yy47
	}
yy189:
	in.cursor += 1
yyFillLabel103:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel103
			}
		}
		goto yy48
	case 'e':
		goto yy217
	default:
		goto yy47
	}
yy190:
	in.cursor += 1
yyFillLabel104:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel104
			}
		}
		goto yy191
	}
yy191:
//line "py.re":135
	{ return KEYWORD }
//line "py.go":2523
yy192:
	in.cursor += 1
yyFillLabel105:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel105
			}
		}
		goto yy193
	}
yy193:
//line "py.re":142
	{ return KEYWORD }
//line "py.go":2550
yy194:
	in.cursor += 1
yyFillLabel106:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel106
			}
		}
		goto yy48
	case 'r':
		goto yy219
	default:
		goto yy47
	}
yy195:
	in.cursor += 1
yyFillLabel107:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel107
			}
		}
		goto yy48
	case 's':
		goto yy220
	default:
		goto yy47
	}
yy196:
	in.cursor += 1
yyFillLabel108:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel108
			}
		}
		goto yy48
	case 'i':
		goto yy222
	default:
		goto yy47
	}
yy197:
	in.cursor += 1
yyFillLabel109:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel109
			}
		}
		goto yy198
	}
yy198:
//line "py.re":122
	{ return KEYWORD }
//line "py.go":2628
yy199:
	in.cursor += 1
yyFillLabel110:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel110
			}
		}
		goto yy200
	}
yy200:
//line "py.re":123
	{ return KEYWORD }
//line "py.go":2655
yy201:
	in.cursor += 1
yyFillLabel111:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel111
			}
		}
		goto yy48
	case 'p':
		goto yy223
	default:
		goto yy47
	}
yy202:
	in.cursor += 1
yyFillLabel112:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel112
			}
		}
		goto yy48
	case 'l':
		goto yy224
	default:
		goto yy47
	}
yy203:
	in.cursor += 1
yyFillLabel113:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel113
			}
		}
		goto yy204
	}
yy204:
//line "py.re":128
	{ return KEYWORD }
//line "py.go":2716
yy205:
	in.cursor += 1
yyFillLabel114:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel114
			}
		}
		goto yy48
	case 'a':
		goto yy225
	default:
		goto yy47
	}
yy206:
	in.cursor += 1
yyFillLabel115:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel115
			}
		}
		goto yy48
	case 'r':
		goto yy226
	default:
		goto yy47
	}
yy207:
	in.cursor += 1
yyFillLabel116:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel116
			}
		}
		goto yy48
	case 'd':
		goto yy227
	default:
		goto yy47
	}
yy208:
	in.cursor += 1
yyFillLabel117:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel117
			}
		}
		goto yy48
	case 'o':
		goto yy228
	default:
		goto yy47
	}
yy209:
	in.cursor += 1
yyFillLabel118:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel118
			}
		}
		goto yy210
	}
yy210:
//line "py.re":139
	{ return KEYWORD }
//line "py.go":2811
yy211:
	in.cursor += 1
yyFillLabel119:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel119
			}
		}
		goto yy48
	case 'e':
		goto yy229
	default:
		goto yy47
	}
yy212:
	in.cursor += 1
yyFillLabel120:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel120
			}
		}
		goto yy48
	case 'r':
		goto yy231
	default:
		goto yy47
	}
yy213:
	in.cursor += 1
yyFillLabel121:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel121
			}
		}
		goto yy48
	case 'e':
		goto yy232
	default:
		goto yy47
	}
yy214:
	in.cursor += 1
yyFillLabel122:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel122
			}
		}
		goto yy215
	}
yy215:
//line "py.re":145
	{ return KEYWORD }
//line "py.go":2889
yy216:
	in.cursor += 1
yyFillLabel123:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel123
			}
		}
		goto yy48
	case 'd':
		goto yy234
	default:
		goto yy47
	}
yy217:
	in.cursor += 1
yyFillLabel124:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel124
			}
		}
		goto yy218
	}
yy218:
//line "py.re":125
	{ return KEYWORD }
//line "py.go":2933
yy219:
	in.cursor += 1
yyFillLabel125:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel125
			}
		}
		goto yy48
	case 't':
		goto yy236
	default:
		goto yy47
	}
yy220:
	in.cursor += 1
yyFillLabel126:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel126
			}
		}
		goto yy221
	}
yy221:
//line "py.re":118
	{ return KEYWORD }
//line "py.go":2977
yy222:
	in.cursor += 1
yyFillLabel127:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel127
			}
		}
		goto yy48
	case 'n':
		goto yy238
	default:
		goto yy47
	}
yy223:
	in.cursor += 1
yyFillLabel128:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel128
			}
		}
		goto yy48
	case 't':
		goto yy239
	default:
		goto yy47
	}
yy224:
	in.cursor += 1
yyFillLabel129:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel129
			}
		}
		goto yy48
	case 'l':
		goto yy241
	default:
		goto yy47
	}
yy225:
	in.cursor += 1
yyFillLabel130:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel130
			}
		}
		goto yy48
	case 'l':
		goto yy242
	default:
		goto yy47
	}
yy226:
	in.cursor += 1
yyFillLabel131:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel131
			}
		}
		goto yy48
	case 't':
		goto yy244
	default:
		goto yy47
	}
yy227:
	in.cursor += 1
yyFillLabel132:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel132
			}
		}
		goto yy48
	case 'a':
		goto yy246
	default:
		goto yy47
	}
yy228:
	in.cursor += 1
yyFillLabel133:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel133
			}
		}
		goto yy48
	case 'c':
		goto yy248
	default:
		goto yy47
	}
yy229:
	in.cursor += 1
yyFillLabel134:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel134
			}
		}
		goto yy230
	}
yy230:
//line "py.re":140
	{ return KEYWORD }
//line "py.go":3123
yy231:
	in.cursor += 1
yyFillLabel135:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel135
			}
		}
		goto yy48
	case 'n':
		goto yy249
	default:
		goto yy47
	}
yy232:
	in.cursor += 1
yyFillLabel136:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel136
			}
		}
		goto yy233
	}
yy233:
//line "py.re":144
	{ return KEYWORD }
//line "py.go":3167
yy234:
	in.cursor += 1
yyFillLabel137:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel137
			}
		}
		goto yy235
	}
yy235:
//line "py.re":146
	{ return KEYWORD }
//line "py.go":3194
yy236:
	in.cursor += 1
yyFillLabel138:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel138
			}
		}
		goto yy237
	}
yy237:
//line "py.re":117
	{ return KEYWORD }
//line "py.go":3221
yy238:
	in.cursor += 1
yyFillLabel139:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel139
			}
		}
		goto yy48
	case 'u':
		goto yy251
	default:
		goto yy47
	}
yy239:
	in.cursor += 1
yyFillLabel140:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel140
			}
		}
		goto yy240
	}
yy240:
//line "py.re":124
	{ return KEYWORD }
//line "py.go":3265
yy241:
	in.cursor += 1
yyFillLabel141:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel141
			}
		}
		goto yy48
	case 'y':
		goto yy252
	default:
		goto yy47
	}
yy242:
	in.cursor += 1
yyFillLabel142:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel142
			}
		}
		goto yy243
	}
yy243:
//line "py.re":129
	{ return KEYWORD }
//line "py.go":3309
yy244:
	in.cursor += 1
yyFillLabel143:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel143
			}
		}
		goto yy245
	}
yy245:
//line "py.re":131
	{ return KEYWORD }
//line "py.go":3336
yy246:
	in.cursor += 1
yyFillLabel144:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel144
			}
		}
		goto yy247
	}
yy247:
//line "py.re":134
	{ return KEYWORD }
//line "py.go":3363
yy248:
	in.cursor += 1
yyFillLabel145:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel145
			}
		}
		goto yy48
	case 'a':
		goto yy254
	default:
		goto yy47
	}
yy249:
	in.cursor += 1
yyFillLabel146:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel146
			}
		}
		goto yy250
	}
yy250:
//line "py.re":141
	{ return KEYWORD }
//line "py.go":3407
yy251:
	in.cursor += 1
yyFillLabel147:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel147
			}
		}
		goto yy48
	case 'e':
		goto yy255
	default:
		goto yy47
	}
yy252:
	in.cursor += 1
yyFillLabel148:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel148
			}
		}
		goto yy253
	}
yy253:
//line "py.re":126
	{ return KEYWORD }
//line "py.go":3451
yy254:
	in.cursor += 1
yyFillLabel149:
	yych = peek(in)
	switch (yych) {
	case 0x00:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel149
			}
		}
		goto yy48
	case 'l':
		goto yy257
	default:
		goto yy47
	}
yy255:
	in.cursor += 1
yyFillLabel150:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel150
			}
		}
		goto yy256
	}
yy256:
//line "py.re":119
	{ return KEYWORD }
//line "py.go":3495
yy257:
	in.cursor += 1
yyFillLabel151:
	yych = peek(in)
	switch (yych) {
	case '$':
		fallthrough
	case '0','1','2','3','4','5','6','7','8','9':
		fallthrough
	case 'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z':
		fallthrough
	case '_':
		fallthrough
	case 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z':
		goto yy46
	default:
		if (in.limit <= in.cursor + 1) {
			if (fill(in) == 0) {
				goto yyFillLabel151
			}
		}
		goto yy258
	}
yy258:
//line "py.re":136
	{ return KEYWORD }
//line "py.go":3522
yy259:
//line "py.re":97
	{ return END }
//line "py.go":3526
}
//line "py.re":182

    }
}

func init() {
	Register([]string{".py"}, py_lex)
}